# Generated by Django 3.2.5 on 2022-06-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='previous_action',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
