# Generated by Django 3.2.5 on 2022-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_workflowitems_previous_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowitems',
            name='previous_action',
        ),
        migrations.AddField(
            model_name='workevents',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
