# Generated by Django 3.2.5 on 2022-09-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220915_1528'),
        ('transaction', '0003_programs_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairings',
            name='counterparty_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.counterparty'),
        ),
    ]
