# Generated by Django 3.2.5 on 2022-07-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220704_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
