# Generated by Django 3.2.5 on 2022-09-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220926_1500'),
        ('transaction', '0005_auto_20220926_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairings',
            name='counterparty_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.counterparty'),
        ),
    ]
