# Generated by Django 3.2.5 on 2022-09-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_counterparty_onboarding'),
        ('transaction', '0006_alter_pairings_counterparty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='counterparty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.counterparty'),
        ),
    ]
