# Generated by Django 3.2.5 on 2022-09-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_workflowitems_counterparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowitems',
            name='counterparty',
        ),
    ]
