# Generated by Django 3.2.5 on 2022-10-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_parties_status'),
        ('transaction', '0008_remove_workflowitems_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='counterparty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.counterparty'),
        ),
    ]
