# Generated by Django 3.2.5 on 2022-06-14 09:40

from django.db import migrations, models
import django.db.models.deletion
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_auto_20220610_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceuploads',
            name='attached_file',
        ),
        migrations.RemoveField(
            model_name='pairings',
            name='attached_file',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='attached_file',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to=transaction.models.manage_scf_attachments)),
                ('invoice_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceuploads')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.pairings')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.programs')),
            ],
        ),
    ]
