# Generated by Django 3.2.5 on 2022-06-14 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20220614_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='invoice_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceuploads'),
        ),
        migrations.AlterField(
            model_name='file',
            name='pairing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.pairings'),
        ),
        migrations.AlterField(
            model_name='file',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.programs'),
        ),
    ]
