# Generated by Django 3.2.5 on 2022-10-06 17:38

import accounts.file_path
import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=55)),
                ('bank', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Action',
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('dial_code', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.IntegerField()),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=155)),
                ('api_route', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Model',
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=35, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=35, null=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('BANK', 'BANK'), ('OTHER', 'OTHER'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER'), ('OTHER', 'OTHER')], max_length=25)),
                ('status', models.CharField(choices=[('NONE', 'NONE'), ('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], max_length=255)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries')),
            ],
            options={
                'verbose_name_plural': 'Party',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='signupprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=35, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=35, null=True)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('party_type', models.CharField(default='BUYER', max_length=25)),
                ('status', models.CharField(choices=[('NONE', 'NONE'), ('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], max_length=255)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries')),
            ],
        ),
        migrations.CreateModel(
            name='signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=55)),
                ('sign_a', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_b', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_c', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
            ],
            options={
                'verbose_name_plural': 'Signatures',
            },
        ),
        migrations.CreateModel(
            name='Partyaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34)),
                ('account_with_bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.banks')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.currencies')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.parties')),
            ],
            options={
                'verbose_name_plural': 'PartyAccounts',
            },
        ),
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('onboarding', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('SENT TO BANK', 'SENT TO BANK'), ('SENT TO COUNTERPARTY', 'SENT TO COUNTERPARTY'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], max_length=25, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=18, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=18, null=True)),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries')),
            ],
            options={
                'verbose_name_plural': 'CounterParty',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='banks',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=accounts.file_path.profile_img_path)),
                ('is_administrator', models.BooleanField(default=False)),
                ('is_master_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.counterparty')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='userprocessauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=55)),
                ('data_entry', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_a', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_b', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_c', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'userprocessauth',
                'unique_together': {('action', 'user', 'model')},
            },
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['id'], name='accounts_si_id_c21b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['model'], name='accounts_si_model_f4a2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['action'], name='accounts_si_action__2ad824_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['party'], name='accounts_si_party_i_30c476_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signatures',
            unique_together={('model', 'action', 'party')},
        ),
        migrations.AlterUniqueTogether(
            name='parties',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone', 'email')},
        ),
    ]
