# Generated by Django 3.2.5 on 2022-06-22 09:35

import accounts.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to=accounts.file_path.profile_img_path),
        ),
    ]
