# Generated by Django 3.2.5 on 2022-10-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupprocess',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupprocess',
            name='phone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
