# Generated by Django 3.2.5 on 2022-09-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220915_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='gst_no',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='pan_no',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
