# Generated by Django 3.2.5 on 2022-07-22 09:48

import accounts.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='static/images/avatar.jpg', null=True, upload_to=accounts.file_path.profile_img_path),
        ),
        migrations.AlterUniqueTogether(
            name='signatures',
            unique_together={('model', 'action', 'party')},
        ),
    ]
