# Generated by Django 3.2.5 on 2022-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220915_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
