# Generated by Django 3.2.5 on 2022-09-12 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220722_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_type',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('BANK', 'BANK'), ('OTHER', 'OTHER'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER'), ('OTHER', 'OTHER')], max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='userprocessauth',
            unique_together={('action', 'user', 'model')},
        ),
        migrations.CreateModel(
            name='CounterParty',
            fields=[
                ('c_id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('c_name', models.CharField(max_length=255)),
                ('c_address', models.CharField(max_length=255)),
                ('c_city', models.CharField(max_length=255)),
                ('c_country', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_mobile', models.CharField(max_length=10)),
                ('c_onboarding', models.CharField(choices=[('DRAFT', 'DRAFT'), ('SENT TO BANK', 'SENT TO BANK'), ('SENT TO COUNTERPARTY', 'SENT TO COUNTERPARTY'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], max_length=25)),
                ('gst_no', models.CharField(max_length=18)),
                ('pan_no', models.CharField(max_length=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
