# Generated by Django 3.2.5 on 2022-09-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parties_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='status',
        ),
    ]
