# Generated by Django 3.2.5 on 2022-09-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_parties_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], default=('NEW', 'NEW'), max_length=255),
        ),
    ]
