# Generated by Django 3.2.5 on 2022-09-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220912_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='counterparty',
            old_name='c_onboarding',
            new_name='onboarding',
        ),
    ]
