# Generated by Django 3.2.5 on 2022-09-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220912_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
