# Generated by Django 3.2.5 on 2022-09-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220912_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='user',
        ),
    ]
