# Generated by Django 3.2.5 on 2022-09-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_parties_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], default='NEW', max_length=255),
        ),
    ]
