# Generated by Django 3.2.5 on 2022-09-13 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_id_counterparty_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='country',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='country_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries'),
        ),
    ]
