# Generated by Django 3.2.5 on 2022-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_parties_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterparty',
            options={'ordering': ['id'], 'verbose_name_plural': 'CounterParty'},
        ),
        migrations.AlterUniqueTogether(
            name='counterparty',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='parties',
            unique_together={('name', 'city')},
        ),
    ]
