# Generated by Django 3.2.5 on 2022-09-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220926_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone', 'email')},
        ),
    ]
