# Generated by Django 3.2.5 on 2022-09-28 06:58

import accounts.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220928_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.file_path.profile_img_path),
        ),
    ]
