# Generated by Django 3.2.5 on 2022-09-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='account_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
