# Generated by Django 3.2.5 on 2022-09-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_parties_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.counterparty'),
        ),
    ]
