# Generated by Django 3.2.5 on 2022-09-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_counterparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='onboarding',
            field=models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('SENT TO BANK', 'SENT TO BANK'), ('SENT TO COUNTERPARTY', 'SENT TO COUNTERPARTY'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], max_length=25, null=True),
        ),
    ]
