# Generated by Django 3.2.5 on 2022-10-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_parties_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupprocess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=35, null=True)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(blank=True, max_length=6, null=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('party_type', models.CharField(blank=True, default='BUYER', max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('NONE', 'NONE'), ('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ONBOARDED', 'ONBOARDED'), ('DEACTIVATED', 'DEACTIVATED')], max_length=255, null=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries')),
            ],
        ),
    ]
