# Generated by Django 3.2.5 on 2022-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_signupprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
