# Generated by Django 3.2.5 on 2022-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_parties_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
